import { Meteor } from 'meteor/meteor';
import Project from '/imports/model/project';

const addTask = function(taskDefinition, childs) {
  const id = Tasks.insert(_.extend(taskDefinition, {
    isChild: !childs
  }));

  _.each(childs, function(child) {
    Tasks.update({_id:child._id}, {$set:{parent:id}});
  });
  return Tasks.findOne({_id:id});
};


Meteor.startup(() => {
  Projects.find({label:'Gui & Lu (auto)'}).forEach((project) => {
      project.remove();
  });

  const project = Project.create(
    'Gui & Lu (auto)',
    'Construccion de casa unifamiliar de 324m',
    {
      _id:'55PROJECT44ID'
    }
  );

  const quote = project.createQuote("Initial", "Autogenerated", {
    _id: '33QUOTE22ID'
  });
  QuoteItems.remove({});

  const subsuelo = quote.addChild('Subsuelo');
  subsuelo.addChild("Armado de vigas", { hours:40,  material:15 });
  subsuelo.addChild("Armado de columnas", { hours:40,  material:15 });
  subsuelo.addChild("Llenado de vigas", { hours:20,  material:40 });
  subsuelo.addChild("Llenado de columnas", { hours:20,  material:45 });

  const fundacion = subsuelo.addChild("Fundacion");
  fundacion.addChild("Armado de zapatas", { hours:10, material:100  });
  fundacion.addChild("Llenado", { hours:4,  material:150 });

  const plantaBaja = quote.addChild('Planta baja');
  plantaBaja.addChild("Armado de vigas", { hours:80,  material:30 });
  plantaBaja.addChild("Armado de columnas", { hours:80,  material:30 });
  plantaBaja.addChild("Llenado de vigas", { hours:40,  material:60 });
  plantaBaja.addChild("Llenado de columnas", { hours:40,  material:60 });

  const plantaAlta = quote.addChild('Planta Alta');
  plantaAlta.addChild("Armado de vigas", { hours:40,  material:15 });
  plantaAlta.addChild("Armado de columnas", { hours:40,  material:15 });
  plantaAlta.addChild("Llenado de vigas", { hours:20,  material:40 });
  plantaAlta.addChild("Llenado de columnas", { hours:20,  material:45 });

  quote.freeze();

  project.start(quote);
});
